### ISSUE TITLE
Is the model fine tuned on some dataset? If yes can I know which dataset and why didn't you show code for finetuning Pretrained model :(

### ISSUE THREAD

**Issue by kishan2k2** [Panitnun-6243/text_based_emotion_recognition#1]

**Comment by Panitnun-6243** [comment]
You can find another resource from this link: https://drive.google.com/drive/folders/1RyYfoGakquHZIst0UrXDf466MhbQdjCf?usp=sharing
It contains a notebook that I use to train the model. About the dataset, I use "Twitter Text Emotion" dataset from Kaggle.
